# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"openImageCV2": "00_core.ipynb",
         "plotCV2": "00_core.ipynb",
         "putText": "00_core.ipynb",
         "getDateTimePictureTaken": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://eandreas.github.io/timelapse/"

git_url = "https://github.com/eandreas/timelapse/tree/main/"

def custom_doc_links(name): return None
